
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buhhwpjmlsrbaxisshht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aGh3cGptbHNyYmF4aXNzaGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Mzg4NjgsImV4cCI6MjA2MTQxNDg2OH0.yUhFhbmTs92zb8gtuFKdyZVeX8v3xQ8JvcHffECH_Wg";

// Get the current URL for redirect purposes
const getURL = () => {
  // Check if window is defined (browser) or not (SSR)
  if (typeof window !== 'undefined') {
    return window.location.origin;
  }
  // Fallback for non-browser environments
  return 'https://buhhwpjmlsrbaxisshht.supabase.co';
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
    detectSessionInUrl: true
  }
});
